print(" *", end="")
print(" * ","talves queita deitar"," venha deita então" ,"*" , sep="%")
print(" * *")
print(" * *")
print("*** ***")
print(" * *")
print(" * *")
print(" *****")
print( "peixe", "salgadinhos" ,sep="&")
print(0x123)